
TYPE
	brdk_json_find_typ : 
		( (*JSON find type.*)
		BRDK_JSON_OBJECT_START := 0, (*JSON object start {.*)
		BRDK_JSON_OBJECT_END := 1, (*JSON object end }.*)
		BRDK_JSON_ARRAY_START := 2, (*JSON array start [.*)
		BRDK_JSON_ARRAY_ELEMENT := 4, (*JSON array element ,.*)
		BRDK_JSON_ARRAY_END := 5, (*JSON array end ].*)
		BRDK_JSON_OBJECT_VALUE := 6, (*JSON value :.*)
		BRDK_JSON_SOURCE_END := 7 (*JSON source end NULL.*)
		);
	brdk_json_dt_typ : 
		( (*JSON datatype.*)
		BRDK_JSON_STRING_TO_STRING := 0, (*STRING -> STRING.*)
		BRDK_JSON_STRING_TO_DINT := 1, (*STRING -> DINT.*)
		BRDK_JSON_STRING_TO_UDINT := 2, (*STRING -> UDINT.*)
		BRDK_JSON_STRING_TO_REAL := 3, (*STRING -> REAL.*)
		BRDK_JSON_STRING_TO_BOOL := 4, (*STRING -> BOOL.*)
		BRDK_JSON_DINT_TO_STRING := 5, (*DINT -> STRING.*)
		BRDK_JSON_DINT_TO_DINT := 6, (*DINT -> DINT.*)
		BRDK_JSON_DINT_TO_BOOL := 7, (*DINT -> BOOL.*)
		BRDK_JSON_UDINT_TO_STRING := 8, (*UDINT -> STRING.*)
		BRDK_JSON_UDINT_TO_UDINT := 9, (*UDINT -> UDINT.*)
		BRDK_JSON_UDINT_TO_BOOL := 10, (*UDINT -> BOOL.*)
		BRDK_JSON_BOOL_TO_STRING := 11, (*BOOL -> STRING.*)
		BRDK_JSON_BOOL_TO_DINT := 12, (*BOOL -> DINT.*)
		BRDK_JSON_BOOL_TO_UDINT := 13, (*BOOL -> UDINT.*)
		BRDK_JSON_BOOL_TO_BOOL := 14, (*BOOL -> BOOL.*)
		BRDK_JSON_REAL_TO_REAL := 15, (*REAL -> REAL.*)
		BRDK_JSON_REAL_TO_STRING := 16 (*REAL -> STRING.*)
		);
END_TYPE
